# Generated by Django 3.2.5 on 2021-08-03 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarForSale',
            fields=[
                ('car_for_sale_id', models.IntegerField(primary_key=True, serialize=False)),
                ('manufacturers', models.CharField(blank=True, max_length=20, null=True)),
                ('asking_price', models.FloatField(blank=True, null=True)),
                ('date_acquired', models.DateTimeField(blank=True, null=True)),
                ('reg_year', models.DateTimeField(blank=True, null=True)),
                ('other_details', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'car_for_sale',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CarLoan',
            fields=[
                ('loan_id', models.IntegerField(primary_key=True, serialize=False)),
                ('loan_amount', models.FloatField(blank=True, null=True)),
                ('other_details', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'car_loan',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CarModels',
            fields=[
                ('car_model_code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('manufacturer_code', models.CharField(blank=True, max_length=20, null=True)),
                ('model_name', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'car_models',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CarSold',
            fields=[
                ('car_sold_id', models.IntegerField(primary_key=True, serialize=False)),
                ('sold_price', models.FloatField(blank=True, null=True)),
                ('sold_date', models.DateTimeField(blank=True, null=True)),
                ('payment', models.FloatField(blank=True, null=True)),
                ('purchased_price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'car_sold',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.IntegerField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(blank=True, max_length=20, null=True)),
                ('cell_number', models.CharField(blank=True, max_length=10, null=True)),
                ('email', models.CharField(blank=True, max_length=30, null=True)),
                ('town_city', models.CharField(blank=True, max_length=50, null=True)),
                ('province', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'db_table': 'customer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerPayment',
            fields=[
                ('customer_payment_id', models.IntegerField(primary_key=True, serialize=False)),
                ('customer_payment_date_due', models.DateTimeField(blank=True, null=True)),
                ('customer_payemnt_date', models.DateTimeField(blank=True, null=True)),
                ('customer_payment_amt', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'customer_payment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('employee_id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=40, null=True)),
                ('last_name', models.CharField(blank=True, max_length=30, null=True)),
                ('address', models.CharField(blank=True, max_length=40, null=True)),
                ('email', models.CharField(blank=True, max_length=30, null=True)),
                ('phone', models.CharField(blank=True, max_length=10, null=True)),
                ('salary', models.FloatField(blank=True, null=True)),
                ('joined_date', models.DateTimeField(blank=True, null=True)),
                ('total_leave', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'employees',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FinanceCompany',
            fields=[
                ('finance_company_id', models.IntegerField(primary_key=True, serialize=False)),
                ('finance_company_name', models.CharField(blank=True, max_length=20, null=True)),
                ('other_details', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'finance_company',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InsuranceCompany',
            fields=[
                ('insurance_company_id', models.IntegerField(primary_key=True, serialize=False)),
                ('insurance_company_name', models.CharField(blank=True, max_length=20, null=True)),
                ('other_details', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'insurance_company',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InsurancePolicies',
            fields=[
                ('policy_id', models.IntegerField(primary_key=True, serialize=False)),
                ('policy_start_date', models.DateTimeField(blank=True, null=True)),
                ('monthly_payments', models.FloatField(blank=True, null=True)),
                ('other_details', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'insurance_policies',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Servicing',
            fields=[
                ('servicing_id', models.IntegerField(primary_key=True, serialize=False)),
                ('total_servicing_offered', models.IntegerField(blank=True, null=True)),
                ('servicing_used', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'servicing',
                'managed': False,
            },
        ),
    ]
